#====<< Markdown >>============================================================>
[[language]]
name = "markdown"
soft-wrap.enable = true
soft-wrap.wrap-indicator = ""
soft-wrap.wrap-at-text-width = true

#====<< Nix >>=================================================================>
[[language]]
name = "nix"
language-servers = [ "nixd", "nil" ] # Makes `nixd` take priority
